apiVersion: v1
kind: Service
metadata:
  name: todo-react-service
spec:
  selector:
    app: todo-react
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 3000
      nodePort: 30111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-react
  labels:
    app: todo-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-react
  template:
    metadata:
      labels:
        app: todo-react
    spec:
      containers:
      - name: todo-react
        imagePullPolicy: Never
        image: todo-react:latest
        ports:
        - containerPort: 3000
        
      
